kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 5432
    hostPort: 5432
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 3001
    hostPort: 3001
    listenAddress: "0.0.0.0"
    protocol: tcp
