apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: k8s-demo
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: web
    targetPort: http
    protocol: TCP
  selector:
    app: k8s-demo
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app:  k8s-demo
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-demo
        tier: backend
    spec:
      containers:
        - name:  k8s-demo
          image: "krishchow/k8s-backend:latest"
          ports:
            - name: http
              containerPort: 3000
          env:
          - name: PGHOST
            value: my-release-postgresql.default.svc.cluster.local # my-release-postgresql would also work
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: my-release-postgresql
                key: postgresql-password
          - name: PGUSER
            value: postgres
          - name: PGDATABASE
            value: postgres
          - name: PORT
            value: "3000"
