apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: k8s-demo
spec:
  ports:
  - port: 3001
    name: web
  selector:
    app: backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: k8s-demo
  serviceName: "backend"
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: backend
        image: krishchow/k8s-backend:latest
        ports:
        - containerPort: 3001
          name: web
        volumeMounts:
        - name: file-data
          mountPath: /data
        env:
        - name: PGHOST
          value: my-release-postgresql.default.svc.cluster.local
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: my-release-postgresql
              key: postgresql-password
        - name: PGUSER
          value: postgres
        - name: PGDATABASE
          value: postgres
  volumeClaimTemplates:
  - metadata:
      name: file-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
