apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: k8s-demo
spec:
  type: NodePort
  ports:
  - port: 3001
    name: web
    targetPort: http
    protocol: TCP
  selector:
    app: k8s-demo
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app:  k8s-demo
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-demo
        tier: backend
    spec:
      containers:
        - name:  k8s-demo
          image: "krishchow/k8s-backend:latest"
          ports:
            - name: http
              containerPort: 3001