apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: k8s-demo
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: web
    targetPort: http
    protocol: TCP
  selector:
    app: k8s-demo
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app:  k8s-demo
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-demo
        tier: frontend
    spec:
      containers:
        - name:  k8s-demo
          image: "krishchow/k8s-frontend:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
          - name: NEXT_PUBLIC_BACKEND_URL
            value: "127.0.0.1"
