apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: k8s-demo
spec:
  type: NodePort
  ports:
  - port: 5000
    name: web
    targetPort: http
    protocol: TCP
    nodePort: 30001
  selector:
    app: k8s-demo
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app:  k8s-demo
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-demo
        tier: frontend
    spec:
      containers:
        - name:  k8s-demo
          image: "krishchow/k8s-frontend:latest"
          ports:
            - name: http
              containerPort: 5000